version: '3'
services:
  simplesamlphp:
    build:
      context: .
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=saml-poc
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:5111/Saml2/Acs
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://localhost:5111/Saml2/Logout
      - SIMPLESAMLPHP_SP_NAMEID_FORMAT=urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
